name: Build EXE and Upload to Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --name TradingOrderExecutor --onefile main.py

      - name: Upload EXE to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TradingOrderExecutor-EXE
          path: dist/TradingOrderExecutor.exe
